Map m1 = {
  "status": "200",
  "success": "1",
  "message": "Record Found.",
  "data": [
    {
      "ProductData": [
        {
          "Id": "220",
          "UserId": "2651",
          "UserName": "Ikrima  Hasyima ",
          "UserProfile": "https://s3.us-east-2.amazonaws.com/inunion/1662953393900.jpg",
          "Address": "QV54+R4V, Jl. Kp. Tim., Gn. Samarinda, Kec. Balikpapan Utara, Kota Balikpapan, Kalimantan Timur 76124, Indonesia",
          "ContactNo": "",
          "WebsiteUrl": "",
          "Longitude": "116.8550915",
          "Langitude": "-1.2403967",
          "CategoryName": "Skin Care & Beauty",
          "SubCategoryName": "Cosmetics   ",
          "Name": "mahveen skincare ",
          "Currency": "",
          "MinPrice": "315",
          "MaxPrice": "",
          "DiscountPrice": "315",
          "Weight": "",
          "DeliveryCharge": "0",
          "Description": "Pagi - pagi dapat mood booster kayak begini kan senang  akunya buat aktivitas emang dah skincare terbaik itu cantik nya NATURAL bukan putih kayak tembok \nDan permasalahan flek pun minggat ✌️",
          "Condition": "",
          "Images": "[{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1661900951051.jpg\"},{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1661900959163.jpg\"},{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1661900960614.jpg\"}]",
          "Negotiation": "false",
          "SoldStatus": "Unsold",
          "ProductType": "",
          "UserSince": "August 2022",
          "CreatAt": "31-08-2022",
          "ProductSave": "1",
          "ProductReport": "1",
          "AverageRating": "5",
          "TotalUser": "1"
        },
        {
          "Id": "221",
          "UserId": "2592",
          "UserName": "Dhinar Nugraha",
          "UserProfile": "https://s3.us-east-2.amazonaws.com/inunion/1661398006075.jpg",
          "Address": "76Q4+4J6, KP Ciceureme, Mekargalih, Kec. Cikalongkulon, Kabupaten Cianjur, Jawa Barat 43291, Indonesia",
          "ContactNo": "",
          "WebsiteUrl": "",
          "Longitude": "107.20680970698594",
          "Langitude": "-6.7118025318111245",
          "CategoryName": "Hobbies",
          "SubCategoryName": "Other    ",
          "Name": "Ikan Hias",
          "Currency": "Rupiah",
          "MinPrice": "100000",
          "MaxPrice": "",
          "DiscountPrice": "40000",
          "Weight": "",
          "DeliveryCharge": "0",
          "Description": "Ikan Hias Cupang",
          "Condition": "",
          "Images": "[{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1661912631123.jpg\"},{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1661912635571.jpg\"},{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1661912636308.jpg\"},{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1661912637022.jpg\"},{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1661912637821.jpg\"}]",
          "Negotiation": "false",
          "SoldStatus": "Unsold",
          "ProductType": "",
          "UserSince": "August 2022",
          "CreatAt": "31-08-2022",
          "ProductSave": "1",
          "ProductReport": "1",
          "AverageRating": "0",
          "TotalUser": "0"
        },
        {
          "Id": "222",
          "UserId": "2169",
          "UserName": "AN Nisha",
          "UserProfile": "https://s3.us-east-2.amazonaws.com/inunion/1663445690617.jpg",
          "Address": "RHOA3701, 3701 Al Athra, 6938، حي العليا، Riyadh 12311, Arab Saudi",
          "ContactNo": "",
          "WebsiteUrl": "",
          "Longitude": "46.68004084378481",
          "Langitude": "24.683185568048152",
          "CategoryName": "Skin Care & Beauty",
          "SubCategoryName": "Skin Care    ",
          "Name": "Spakare Spirulina Mask Spakare Spirulina Mask ",
          "Currency": "real Saudi",
          "MinPrice": "50",
          "MaxPrice": "",
          "DiscountPrice": "50",
          "Weight": "",
          "DeliveryCharge": "0",
          "Description": "Spakare Spirulina Mask adalah masker wajah yg bermanfaat untk melembabkan dan mncrhkn wajah, srta memudrkan bks cerawat dan flek hitam",
          "Condition": "",
          "Images": "[{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1661942799495.jpg\"},{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1661942802869.jpg\"},{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1661942805928.jpg\"},{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1661942809226.jpg\"}]",
          "Negotiation": "false",
          "SoldStatus": "Unsold",
          "ProductType": "",
          "UserSince": "August 2022",
          "CreatAt": "31-08-2022",
          "ProductSave": "1",
          "ProductReport": "1",
          "AverageRating": "0",
          "TotalUser": "0"
        },
        {
          "Id": "388",
          "UserId": "4140",
          "UserName": "Faiz Mansuri",
          "UserProfile": "https://s3.us-east-2.amazonaws.com/inunion/1683804376875.jpg",
          "Address": "Moinee Foundation, B/40, Shantabag Society, Rehnuma Society, Vishala, Ahmedabad, Gujarat 380007, India",
          "ContactNo": "",
          "WebsiteUrl": "",
          "Longitude": "72.5370480492711",
          "Langitude": "22.992303627666274",
          "CategoryName": "Clothing & Jewelry",
          "SubCategoryName": "Men Clothing    ",
          "Name": "Tshirt",
          "Currency": "",
          "MinPrice": "250",
          "MaxPrice": "",
          "DiscountPrice": "200",
          "Weight": "",
          "DeliveryCharge": "0",
          "Description": "Tshirt for men.",
          "Condition": "",
          "Images": "[{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1685543715591.jpg\"},{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1685543718457.jpg\"}]",
          "Negotiation": "false",
          "SoldStatus": "Unsold",
          "ProductType": "",
          "UserSince": "May 2023",
          "CreatAt": "31-05-2023",
          "ProductSave": "1",
          "ProductReport": "1",
          "AverageRating": "5",
          "TotalUser": "1"
        },
        {
          "Id": "86",
          "UserId": "191",
          "UserName": "Abdul Mas",
          "UserProfile": "",
          "Address": "Jl. Soragan, Cungkuk, Ngestiharjo, Kec. Kasihan, Kabupaten Bantul, Daerah Istimewa Yogyakarta 55184, Indonesia",
          "ContactNo": "",
          "WebsiteUrl": "",
          "Longitude": "110.3483249",
          "Langitude": "-7.787925500000001",
          "CategoryName": "Real Estate",
          "SubCategoryName": "Sale     ",
          "Name": "shop and house for sale in commercial area, Yogyakarta, Indonesia.",
          "Currency": "",
          "MinPrice": "345000",
          "MaxPrice": "",
          "DiscountPrice": "345000",
          "Weight": "",
          "DeliveryCharge": "0",
          "Description": "* shop with commercial license \n2 floors with 2 bathrooms\n* house with 2 floors\n1st floor : car port, terrace, sitting room, living room, dining room, guest room, 2 kitchens, 2 bathrooms, clothesline area.\n2nd floor :\n2 bedrooms, 1 bathroom, sitting room, balcony.\ncontact person WA : 087802087214\n",
          "Condition": "",
          "Images": "[{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1654009842522.jpg\"},{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1654009848880.jpg\"},{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1654009849866.jpg\"},{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1654009850775.jpg\"},{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1654009851415.jpg\"}]",
          "Negotiation": "false",
          "SoldStatus": "Unsold",
          "ProductType": "",
          "UserSince": "May 2022",
          "CreatAt": "31-05-2022",
          "ProductSave": "1",
          "ProductReport": "1",
          "AverageRating": "5",
          "TotalUser": "3"
        },
        {
          "Id": "215",
          "UserId": "2250",
          "UserName": "Perabot Rumah Tangga",
          "UserProfile": "https://s3.us-east-2.amazonaws.com/inunion/1661525528324.jpg",
          "Address": "Cianjur, Kec. Cianjur, Kabupaten Cianjur, Jawa Barat, Indonesia",
          "ContactNo": "",
          "WebsiteUrl": "",
          "Longitude": "107.1425442",
          "Langitude": "-6.8168237",
          "CategoryName": "Home & Garden",
          "SubCategoryName": "Appliances    ",
          "Name": "Chopper Modern",
          "Currency": "",
          "MinPrice": "800000",
          "MaxPrice": "",
          "DiscountPrice": "800000",
          "Weight": "",
          "DeliveryCharge": "0",
          "Description": "Neozen Twin Chopper, alat pencacah modern yang memudahkan aktivitas memasak di dapur kesayangan. Dapat digunakan untuk menggiling daging, bumbu-bumbu dapur, hingga membuat mpasi anak. Dilengkapi dengan mata pisau titanium yang tajam dengan silikon anti slip di bagian bawah wadah, sehingga aman ketika digunakan.",
          "Condition": "",
          "Images": "[{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1661797869200.jpg\"}]",
          "Negotiation": "false",
          "SoldStatus": "Unsold",
          "ProductType": "",
          "UserSince": "August 2022",
          "CreatAt": "30-08-2022",
          "ProductSave": "1",
          "ProductReport": "1",
          "AverageRating": "3.9",
          "TotalUser": "4"
        },
        {
          "Id": "216",
          "UserId": "2982",
          "UserName": "widiyanto",
          "UserProfile": "",
          "Address": "Unnamed Road, 6RMR+QR4, Sepat, Bulu, Kec. Bulu, Kabupaten Sukoharjo, Jawa Tengah 57563, Indonesia",
          "ContactNo": "",
          "WebsiteUrl": "",
          "Longitude": "110.842087",
          "Langitude": "-7.765603799999999",
          "CategoryName": "Clothing & Jewelry",
          "SubCategoryName": "Women Clothing    ",
          "Name": "mukena ",
          "Currency": "USD",
          "MinPrice": "20",
          "MaxPrice": "",
          "DiscountPrice": "20",
          "Weight": "",
          "DeliveryCharge": "0",
          "Description": "mukena\nbahan katun rayon\nadem\nlembut",
          "Condition": "",
          "Images": "[{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1661814770401.jpg\"}]",
          "Negotiation": "false",
          "SoldStatus": "Unsold",
          "ProductType": "",
          "UserSince": "August 2022",
          "CreatAt": "30-08-2022",
          "ProductSave": "1",
          "ProductReport": "1",
          "AverageRating": "3.5",
          "TotalUser": "3"
        },
        {
          "Id": "217",
          "UserId": "2651",
          "UserName": "Ikrima  Hasyima ",
          "UserProfile": "https://s3.us-east-2.amazonaws.com/inunion/1662953393900.jpg",
          "Address": "QV54+R4V, Jl. Kp. Tim., Gn. Samarinda, Kec. Balikpapan Utara, Kota Balikpapan, Kalimantan Timur 76124, Indonesia",
          "ContactNo": "",
          "WebsiteUrl": "",
          "Longitude": "116.85508366674185",
          "Langitude": "-1.2403915754846464",
          "CategoryName": "Skin Care & Beauty",
          "SubCategoryName": "Cosmetics   ",
          "Name": "mahveen skincare punya dr Fauzi dan dr Adisty ",
          "Currency": "",
          "MinPrice": "315",
          "MaxPrice": "",
          "DiscountPrice": "315",
          "Weight": "",
          "DeliveryCharge": "0",
          "Description": "Ini sunscreen yang aku pakai  no bedak2 club udah glowing sunscreen nya juga RINGAN BANGET MASYAA ALLAH\n\npunya dr Fauzi dan dr Adesty \n\nMahveen Mineral White Sunscreen merupakan tabir surya yang berfungsi melindungi kulit wajah dari paparan UV.B dan UV.A . Mengandung SPf 50 dan PA (+++ ) .Menggunakan mineral sunscreen sebagai pilihan yang lebih aman untuk kulit sensitif ( low allergenic ), dilengkapi dengan Niacinamide sebagai whitening agent, Ethy Panthenol sebagai anti irritant, Aloe Vera sebagai shooting agent dan moisturizer.\n\nMenjadikan kulit tampak lebih cerah, sehat, kenyal dan merona dengan mineral pigment yang memberikan efek instant white sehingga wajah terlihat lebih cerah seketika/ dewy saat pengolesan.\n\nCobain yuk sholihah, beri perlindungan terbaik untuk kulit mu ya☺",
          "Condition": "",
          "Images": "[{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1661823726891.jpg\"},{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1661823742318.jpg\"},{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1661823743562.jpg\"}]",
          "Negotiation": "false",
          "SoldStatus": "Unsold",
          "ProductType": "",
          "UserSince": "August 2022",
          "CreatAt": "30-08-2022",
          "ProductSave": "1",
          "ProductReport": "1",
          "AverageRating": "2.4",
          "TotalUser": "4"
        },
        {
          "Id": "218",
          "UserId": "2651",
          "UserName": "Ikrima  Hasyima ",
          "UserProfile": "https://s3.us-east-2.amazonaws.com/inunion/1662953393900.jpg",
          "Address": "QV54+R4V, Jl. Kp. Tim., Gn. Samarinda, Kec. Balikpapan Utara, Kota Balikpapan, Kalimantan Timur 76124, Indonesia",
          "ContactNo": "",
          "WebsiteUrl": "",
          "Longitude": "116.85508534312248",
          "Langitude": "-1.24039191068221",
          "CategoryName": "Skin Care & Beauty",
          "SubCategoryName": "Other    ",
          "Name": "vitamin BRAINQU nutrisi otak dan tumbuh kembang anak ",
          "Currency": "",
          "MinPrice": "85",
          "MaxPrice": "",
          "DiscountPrice": "85",
          "Weight": "",
          "DeliveryCharge": "0",
          "Description": "vitamin BRAINQU vitamin terlaris saat ini \nMasyaa allah vitamin satu ini..\nAlhamdulillah anak2 ku selama konsumsi vitamin BRAINQU ini bisa di bilang jarang sekali sakit saya sangat bersyukur hingga akhirnya kami menjadi AGEN \n\nWa.me/6287865898841",
          "Condition": "",
          "Images": "[{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1661867797625.jpg\"},{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1661867806158.jpg\"},{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1661867808128.jpg\"},{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1661867809437.jpg\"}]",
          "Negotiation": "false",
          "SoldStatus": "Unsold",
          "ProductType": "",
          "UserSince": "August 2022",
          "CreatAt": "30-08-2022",
          "ProductSave": "1",
          "ProductReport": "1",
          "AverageRating": "0",
          "TotalUser": "0"
        },
        {
          "Id": "219",
          "UserId": "2250",
          "UserName": "Perabot Rumah Tangga",
          "UserProfile": "https://s3.us-east-2.amazonaws.com/inunion/1661525528324.jpg",
          "Address": "Cianjur, Kec. Cianjur, Kabupaten Cianjur, Jawa Barat, Indonesia",
          "ContactNo": "",
          "WebsiteUrl": "",
          "Longitude": "107.1425442",
          "Langitude": "-6.8168237",
          "CategoryName": "Home & Garden",
          "SubCategoryName": "Appliances    ",
          "Name": "Panci Cookware",
          "Currency": "",
          "MinPrice": "555000",
          "MaxPrice": "",
          "DiscountPrice": "5000",
          "Weight": "",
          "DeliveryCharge": "0",
          "Description": "Material berupa forged aluminium dengan lapisan anti lengket\n• Food grade, dan BPA Free\n• Bebas PFOA dan cadmium. Bebas dari bahan-bahan kimia berbahaya sehingga aman digunakan untuk memasak\n• Lapisan luar panci dilapisi dengan lapisan tahan panas\n• Material knob berupa silicone dan handle yang tahan panas serta nyaman digenggam\n• Dilengkapi dengan induction bottom, sehingga dapat digunakan di segala jenis kompor , seperti kompor gas, kompor listrik , kompor induksi , dan lainnya .\n• Tahan panas hingga 240° C\n\n1 Set Terdiri dari :\n• 24 cm casserole\n• 24 cm fry pan\n• Flat Tempered Glass Lid with Silicone Edge\n• 1 Nylon Spatula",
          "Condition": "",
          "Images": "[{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1661869576231.jpg\"},{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1661869579680.jpg\"}]",
          "Negotiation": "false",
          "SoldStatus": "Unsold",
          "ProductType": "",
          "UserSince": "August 2022",
          "CreatAt": "30-08-2022",
          "ProductSave": "1",
          "ProductReport": "1",
          "AverageRating": "5",
          "TotalUser": "2"
        },
        {
          "Id": "359",
          "UserId": "3979",
          "UserName": "aakif pathan",
          "UserProfile": "",
          "Address": "Moinee Foundation, B/40, Shantabag Society, Rehnuma Society, Vishala, Ahmedabad, Gujarat 380007, India",
          "ContactNo": "",
          "WebsiteUrl": "",
          "Longitude": "72.53717377781868",
          "Langitude": "22.992310726406714",
          "CategoryName": "Real Estate",
          "SubCategoryName": "Rent    ",
          "Name": "food ball",
          "Currency": "USD",
          "MinPrice": "123",
          "MaxPrice": "",
          "DiscountPrice": "12",
          "Weight": "",
          "DeliveryCharge": "0",
          "Description": "best",
          "Condition": "",
          "Images": "[{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1669716126664.jpg\"},{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1669716131855.jpg\"}]",
          "Negotiation": "false",
          "SoldStatus": "Unsold",
          "ProductType": "",
          "UserSince": "November 2022",
          "CreatAt": "29-11-2022",
          "ProductSave": "1",
          "ProductReport": "1",
          "AverageRating": "3.5",
          "TotalUser": "2"
        },
        {
          "Id": "353",
          "UserId": "3672",
          "UserName": "Fedrik Juliansyah",
          "UserProfile": "https://s3.us-east-2.amazonaws.com/inunion/1666394014217.jpg",
          "Address": "Jl. Gn Salak No.129, Kecapi, Kec. Harjamukti, Kota Cirebon, Jawa Barat 45142, Indonesia",
          "ContactNo": "",
          "WebsiteUrl": "",
          "Longitude": "108.5550017",
          "Langitude": "-6.7511885",
          "CategoryName": "Family",
          "SubCategoryName": "Other ",
          "Name": "fat milkfish",
          "Currency": "",
          "MinPrice": "1.34",
          "MaxPrice": "",
          "DiscountPrice": "1.34",
          "Weight": "",
          "DeliveryCharge": "0",
          "Description": "ready to eat fish with soft bones",
          "Condition": "",
          "Images": "[{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1667016353883.jpg\"},{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1667016359222.jpg\"},{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1667016360199.jpg\"},{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1667016361374.jpg\"}]",
          "Negotiation": "false",
          "SoldStatus": "Unsold",
          "ProductType": "",
          "UserSince": "October 2022",
          "CreatAt": "29-10-2022",
          "ProductSave": "1",
          "ProductReport": "1",
          "AverageRating": "5",
          "TotalUser": "1"
        },
        {
          "Id": "322",
          "UserId": "3618",
          "UserName": "yuda Kama Jaya",
          "UserProfile": "https://s3.us-east-2.amazonaws.com/inunion/1664406388914.jpg",
          "Address": "2G7V+6H8, Jl. Nasional III, Pelabuhanratu, Kec. Pelabuhanratu, Kabupaten Sukabumi, Jawa Barat 43364, Indonesia",
          "ContactNo": "",
          "WebsiteUrl": "",
          "Longitude": "106.5438873320818",
          "Langitude": "-6.987023821923019",
          "CategoryName": "Family",
          "SubCategoryName": "Other ",
          "Name": "produk rumahan",
          "Currency": "",
          "MinPrice": "60",
          "MaxPrice": "",
          "DiscountPrice": "60",
          "Weight": "",
          "DeliveryCharge": "0",
          "Description": "500ons = 10rb\n1/2 = 35rb\n1kg =65rb",
          "Condition": "",
          "Images": "[{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1664406873553.jpg\"},{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1664406877520.jpg\"},{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1664406878390.jpg\"},{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1664406879203.jpg\"},{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1664406880026.jpg\"}]",
          "Negotiation": "false",
          "SoldStatus": "Unsold",
          "ProductType": "",
          "UserSince": "September 2022",
          "CreatAt": "29-09-2022",
          "ProductSave": "1",
          "ProductReport": "1",
          "AverageRating": "4.5",
          "TotalUser": "2"
        },
        {
          "Id": "212",
          "UserId": "2651",
          "UserName": "Ikrima  Hasyima ",
          "UserProfile": "https://s3.us-east-2.amazonaws.com/inunion/1662953393900.jpg",
          "Address": "QV54+R4V, Jl. Kp. Tim., Gn. Samarinda, Kec. Balikpapan Utara, Kota Balikpapan, Kalimantan Timur 76124, Indonesia",
          "ContactNo": "",
          "WebsiteUrl": "",
          "Longitude": "116.85508634895085",
          "Langitude": "-1.2403915754846464",
          "CategoryName": "Skin Care & Beauty",
          "SubCategoryName": "Cosmetics   ",
          "Name": "mahveen skincare ",
          "Currency": "",
          "MinPrice": "315",
          "MaxPrice": "",
          "DiscountPrice": "315",
          "Weight": "",
          "DeliveryCharge": "0",
          "Description": "Ini sunscreen yang aku pakai  no bedak2 club udah glowing sunscreen nya juga RINGAN BANGET MASYAA ALLAH\n\npunya dr Fauzi dan dr Adesty \n\nMahveen Mineral White Sunscreen merupakan tabir surya yang berfungsi melindungi kulit wajah dari paparan UV.B dan UV.A . Mengandung SPf 50 dan PA (+++ ) .Menggunakan mineral sunscreen sebagai pilihan yang lebih aman untuk kulit sensitif ( low allergenic ), dilengkapi dengan Niacinamide sebagai whitening agent, Ethy Panthenol sebagai anti irritant, Aloe Vera sebagai shooting agent dan moisturizer.\n\nMenjadikan kulit tampak lebih cerah, sehat, kenyal dan merona dengan mineral pigment yang memberikan efek instant white sehingga wajah terlihat lebih cerah seketika/ dewy saat pengolesan.\n\nCobain yuk sholihah, beri perlindungan terbaik untuk kulit mu ya☺",
          "Condition": "",
          "Images": "[{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1661745707491.jpg\"},{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1661745717939.jpg\"},{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1661745719718.jpg\"}]",
          "Negotiation": "false",
          "SoldStatus": "Unsold",
          "ProductType": "",
          "UserSince": "August 2022",
          "CreatAt": "29-08-2022",
          "ProductSave": "1",
          "ProductReport": "1",
          "AverageRating": "0",
          "TotalUser": "0"
        },
        {
          "Id": "213",
          "UserId": "2508",
          "UserName": "Muhammad Wahyudin",
          "UserProfile": "https://s3.us-east-2.amazonaws.com/inunion/1661420642333.jpg",
          "Address": "Bandung, Kota Bandung, Jawa Barat, Indonesia",
          "ContactNo": "",
          "WebsiteUrl": "",
          "Longitude": "107.6191228",
          "Langitude": "-6.9174639",
          "CategoryName": "Clothing & Jewelry",
          "SubCategoryName": "Men Shoes    ",
          "Name": "sendal slop pria",
          "Currency": "",
          "MinPrice": "160000",
          "MaxPrice": "",
          "DiscountPrice": "160000",
          "Weight": "",
          "DeliveryCharge": "0",
          "Description": "sendal slop Naz distro\nterbuat dari bahan Sintetis premium",
          "Condition": "",
          "Images": "[{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1661774320209.jpg\"},{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1661774326754.jpg\"},{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1661774329856.jpg\"},{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1661774332999.jpg\"},{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1661774337261.jpg\"}]",
          "Negotiation": "false",
          "SoldStatus": "Unsold",
          "ProductType": "",
          "UserSince": "August 2022",
          "CreatAt": "29-08-2022",
          "ProductSave": "1",
          "ProductReport": "1",
          "AverageRating": "0",
          "TotalUser": "0"
        },
        {
          "Id": "214",
          "UserId": "1222",
          "UserName": "Sadboy Banjar Dan Sagita",
          "UserProfile": "",
          "Address": "JFNA3986، 3986 حراء، 6363, An Nuzhah District, Jeddah 23534, Saudi Arabia",
          "ContactNo": "",
          "WebsiteUrl": "",
          "Longitude": "39.17095631361008",
          "Langitude": "21.617204286134065",
          "CategoryName": "Skin Care & Beauty",
          "SubCategoryName": "Bath & Body    ",
          "Name": "massage traphy and cupping traphy service at home ",
          "Currency": "",
          "MinPrice": "250",
          "MaxPrice": "",
          "DiscountPrice": "200",
          "Weight": "",
          "DeliveryCharge": "0",
          "Description": "we have massage\nrelaxion\nriydh\nthaild\nswediia\ncupping trehpy\ncup air\nand you want coming we salon whatsapp 05546764331",
          "Condition": "",
          "Images": "[{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1661786124697.jpg\"},{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1661786173483.jpg\"}]",
          "Negotiation": "false",
          "SoldStatus": "Unsold",
          "ProductType": "",
          "UserSince": "August 2022",
          "CreatAt": "29-08-2022",
          "ProductSave": "1",
          "ProductReport": "1",
          "AverageRating": "0",
          "TotalUser": "0"
        },
        {
          "Id": "83",
          "UserId": "148",
          "UserName": "Arif Hakim",
          "UserProfile": "https://s3.us-east-2.amazonaws.com/inunion/1653960667661.jpg",
          "Address": "Jl. Mawar IX No.12, RT.002/RW.013, Bekasi Jaya, Kec. Bekasi Tim., Kota Bks, Jawa Barat 17112, Indonesia",
          "ContactNo": "",
          "WebsiteUrl": "",
          "Longitude": "107.0230402",
          "Langitude": "-6.226054999999999",
          "CategoryName": "Skin Care & Beauty",
          "SubCategoryName": "Fragrance    ",
          "Name": "Oud",
          "Currency": "",
          "MinPrice": "270",
          "MaxPrice": "",
          "DiscountPrice": "265",
          "Weight": "",
          "DeliveryCharge": "0",
          "Description": "make your place good smelt,  peace and fresh",
          "Condition": "",
          "Images": "[{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1653806133079.jpg\"}]",
          "Negotiation": "false",
          "SoldStatus": "Unsold",
          "ProductType": "",
          "UserSince": "May 2022",
          "CreatAt": "29-05-2022",
          "ProductSave": "1",
          "ProductReport": "1",
          "AverageRating": "4.1",
          "TotalUser": "5"
        },
        {
          "Id": "210",
          "UserId": "2503",
          "UserName": "majieL store",
          "UserProfile": "https://s3.us-east-2.amazonaws.com/inunion/1661680052771.jpg",
          "Address": "CF9C+629, Jl. Pemuda II, Pasawahan, Kec. Pasawahan, Kabupaten Purwakarta, Jawa Barat 41172, Indonesia",
          "ContactNo": "",
          "WebsiteUrl": "",
          "Longitude": "107.4701235",
          "Langitude": "-6.581964699999999",
          "CategoryName": "Home & Garden",
          "SubCategoryName": "Other    ",
          "Name": "tanah sawah produktif",
          "Currency": "USD",
          "MinPrice": "250",
          "MaxPrice": "",
          "DiscountPrice": "250",
          "Weight": "",
          "DeliveryCharge": "0",
          "Description": "dijual tanah sawah produktif  bersertifikat luas 2250 perairan ok,,,lokasi kp cihideung blok beubeura desa.pasawahan,kec \n.pasawah, kab.purwakarta, prov.jawabarat",
          "Condition": "",
          "Images": "[{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1661678543591.jpg\"},{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1661678547511.jpg\"}]",
          "Negotiation": "false",
          "SoldStatus": "Unsold",
          "ProductType": "",
          "UserSince": "August 2022",
          "CreatAt": "28-08-2022",
          "ProductSave": "1",
          "ProductReport": "1",
          "AverageRating": "0",
          "TotalUser": "0"
        },
        {
          "Id": "81",
          "UserId": "160",
          "UserName": "Susilo ST",
          "UserProfile": "https://s3.us-east-2.amazonaws.com/inunion/1653430606536.jpg",
          "Address": "Jl. Sidomukti VI No.23, Muktiharjo Kidul, Kec. Pedurungan, Kota Semarang, Jawa Tengah 50197, Indonesia",
          "ContactNo": "",
          "WebsiteUrl": "",
          "Longitude": "110.45987494289875",
          "Langitude": "-6.977556622167261",
          "CategoryName": "Family",
          "SubCategoryName": "Other    ",
          "Name": "Stefiatrully - Natural Sweetener ",
          "Currency": "",
          "MinPrice": "10",
          "MaxPrice": "",
          "DiscountPrice": "10",
          "Weight": "",
          "DeliveryCharge": "0",
          "Description": "Pemanis Alami pengganti Gula tebu dengan kalori 0, sehingga aman bagi pencegahan Diabetes.",
          "Condition": "",
          "Images": "[{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1653715147112.jpg\"},{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1653715151210.jpg\"},{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1653715152204.jpg\"},{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1653715153199.jpg\"}]",
          "Negotiation": "false",
          "SoldStatus": "Unsold",
          "ProductType": "",
          "UserSince": "May 2022",
          "CreatAt": "28-05-2022",
          "ProductSave": "1",
          "ProductReport": "1",
          "AverageRating": "0",
          "TotalUser": "0"
        },
        {
          "Id": "41",
          "UserId": "26",
          "UserName": "سلطان",
          "UserProfile": "https://s3.us-east-2.amazonaws.com/inunion/1646666074791.png",
          "Address": "Prince Turki Bin Abdulaziz? Prince Turki Ibn Abdulaziz Al Awwal Rd, An Nakheel, Riyadh 12382, Saudi Arabia",
          "ContactNo": "",
          "WebsiteUrl": "",
          "Longitude": "46.6354193",
          "Langitude": "24.740393",
          "CategoryName": "Electronics",
          "SubCategoryName": "Mobile    ",
          "Name": "iphone",
          "Currency": "",
          "MinPrice": "500",
          "MaxPrice": "",
          "DiscountPrice": "0",
          "Weight": "",
          "DeliveryCharge": "0",
          "Description": "black iphone",
          "Condition": "",
          "Images": "[{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1643380290859.jpg\"}]",
          "Negotiation": "false",
          "SoldStatus": "Unsold",
          "ProductType": "",
          "UserSince": "January 2022",
          "CreatAt": "28-01-2022",
          "ProductSave": "1",
          "ProductReport": "1",
          "AverageRating": "3.9",
          "TotalUser": "8"
        },
        {
          "Id": "192",
          "UserId": "2250",
          "UserName": "Perabot Rumah Tangga",
          "UserProfile": "https://s3.us-east-2.amazonaws.com/inunion/1661525528324.jpg",
          "Address": "Cianjur, Kec. Cianjur, Kabupaten Cianjur, Jawa Barat, Indonesia",
          "ContactNo": "",
          "WebsiteUrl": "",
          "Longitude": "107.1425442",
          "Langitude": "-6.8168237",
          "CategoryName": "Home & Garden",
          "SubCategoryName": "Appliances    ",
          "Name": "Telpon Set",
          "Currency": "",
          "MinPrice": "1200",
          "MaxPrice": "",
          "DiscountPrice": "1200",
          "Weight": "",
          "DeliveryCharge": "0",
          "Description": "Set cookware lengkap dengan warna colorful\nTerbuat dari material Forged Aluminum\nMemiliki 3 lapisan anti lengket\nDilengkapi dengan gagang yang ergonomis, yang nyaman saat digunakan.\nDapat digunakan untuk segala jenis kompor\nDidesain mewah dan cocok untuk kegiatan masak sehari-hari.\nBPA Free, bebas bahan kimia berbahaya seperti PFOA, LEAD & Cadmium\nFood Grade, aman untuk memasak\nFreezer Safe dan Hot Water safe.\nMemiliki warna pink dan abu-abu, membuat dapur terlihat elegan.\nMudah dibersihkan\n1 Set terdiri dari :\n\nCasserole 20 cm + tutup kaca, kapasitas 3L\nSaucepan 16 cm + tutup kaca, kapasitas 1.5L\nDeep Fry Pan 24cm + tutup kaca, kapasitas 2,6L\nFry Pan 20cm, kapasitas 1.1L\n3 pcs Kitchen Tools ",
          "Condition": "",
          "Images": "[{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1661539018686.jpg\"}]",
          "Negotiation": "false",
          "SoldStatus": "Unsold",
          "ProductType": "",
          "UserSince": "August 2022",
          "CreatAt": "27-08-2022",
          "ProductSave": "1",
          "ProductReport": "1",
          "AverageRating": "4.3",
          "TotalUser": "2"
        },
        {
          "Id": "193",
          "UserId": "2250",
          "UserName": "Perabot Rumah Tangga",
          "UserProfile": "https://s3.us-east-2.amazonaws.com/inunion/1661525528324.jpg",
          "Address": "Cianjur, Kec. Cianjur, Kabupaten Cianjur, Jawa Barat, Indonesia",
          "ContactNo": "",
          "WebsiteUrl": "",
          "Longitude": "107.1425442",
          "Langitude": "-6.8168237",
          "CategoryName": "Home & Garden",
          "SubCategoryName": "Appliances    ",
          "Name": "Hand Blender Ecohome ",
          "Currency": "",
          "MinPrice": "600",
          "MaxPrice": "",
          "DiscountPrice": "600",
          "Weight": "",
          "DeliveryCharge": "0",
          "Description": "Hand blender dengan berbagai fungsi.\nMemiliki material berbahan Stainless Steel.\nDengan mata pisau kuat dan tajam.\nMemiliki mesin yang powerful pure copper.\nDapat menghaluskan bahan makanan dengan cepat dan praktis.\nBisa digunakan untuk membuat ice cream, smoothies dan mengembangkan putih telur.\nMembantu membuat jus tanpa banyak wadah.\nDapat digunakan untuk mencincang daging dengan mudah.\nBisa menghaluskan bumbu tanpa menggunakan banyak air.\nMembuat makanan bayi jadi lebih cepat dan higenis.\nMudah dibersihkan karena dapat dijangkau dengan tangan.\nMemiliki kapasitas 0.8 L\n1 Set Terdiri dari:\n\n1 unit Hand Blender\nDengan Aksesoris tambahan :\n\nChopper Cup\nMeasuring Cup\nWhisker\nMata Pisau \n",
          "Condition": "",
          "Images": "[{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1661539220232.jpg\"},{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1661539221642.jpg\"},{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1661539222301.jpg\"}]",
          "Negotiation": "false",
          "SoldStatus": "Unsold",
          "ProductType": "",
          "UserSince": "August 2022",
          "CreatAt": "27-08-2022",
          "ProductSave": "1",
          "ProductReport": "1",
          "AverageRating": "0",
          "TotalUser": "0"
        },
        {
          "Id": "195",
          "UserId": "2790",
          "UserName": "liza food ",
          "UserProfile": "https://s3.us-east-2.amazonaws.com/inunion/1665004893919.jpg",
          "Address": "PM4X+FQ3, Prince Mashari Ibn Abdulaziz, As Sulimaniyah, Riyadh 12242, Arab Saudi",
          "ContactNo": "",
          "WebsiteUrl": "",
          "Longitude": "46.69936314225197",
          "Langitude": "24.706098038999308",
          "CategoryName": "Skin Care & Beauty",
          "SubCategoryName": "Skin Care    ",
          "Name": "massage therapist spa Indonesia ",
          "Currency": "",
          "MinPrice": "400",
          "MaxPrice": "",
          "DiscountPrice": "300",
          "Weight": "",
          "DeliveryCharge": "0",
          "Description": "massage therapist massage Hot stone massage lobe water relaxing and others ",
          "Condition": "",
          "Images": "[{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1661546494878.jpg\"}]",
          "Negotiation": "false",
          "SoldStatus": "Unsold",
          "ProductType": "",
          "UserSince": "August 2022",
          "CreatAt": "27-08-2022",
          "ProductSave": "1",
          "ProductReport": "1",
          "AverageRating": "0",
          "TotalUser": "0"
        },
        {
          "Id": "196",
          "UserId": "2809",
          "UserName": "Ade Jhi Ghoensa",
          "UserProfile": "https://s3.us-east-2.amazonaws.com/inunion/1661546534426.jpeg",
          "Address": "Kec. Aikmel, Kabupaten Lombok Timur, Nusa Tenggara Bar., Indonesia",
          "ContactNo": "",
          "WebsiteUrl": "",
          "Longitude": "116.5299793",
          "Langitude": "-8.567549999999999",
          "CategoryName": "Clothing & Jewelry",
          "SubCategoryName": "Women Clothing    ",
          "Name": "Bismillah....\n\nDisni maxy\n\nIDR 175.000\n\n*Reseller potongan harga 15.000/item*\n\n✨Minimall Daily✨\n_You",
          "Currency": "",
          "MinPrice": "250",
          "MaxPrice": "",
          "DiscountPrice": "250",
          "Weight": "",
          "DeliveryCharge": "0",
          "Description": "Bismillah....\n\nDisni maxy\n\nIDR 175.000\n\n*Reseller potongan harga 15.000/item*\n\n✨Minimall Daily✨\n_Your simple fashion style_",
          "Condition": "",
          "Images": "[{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1661547438311.jpg\"},{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1661547444231.jpg\"},{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1661547446433.jpg\"},{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1661547448117.jpg\"}]",
          "Negotiation": "false",
          "SoldStatus": "Unsold",
          "ProductType": "",
          "UserSince": "August 2022",
          "CreatAt": "27-08-2022",
          "ProductSave": "1",
          "ProductReport": "1",
          "AverageRating": "0",
          "TotalUser": "0"
        },
        {
          "Id": "197",
          "UserId": "2620",
          "UserName": "Muhammad Harfandi",
          "UserProfile": "https://s3.us-east-2.amazonaws.com/inunion/1663219915198.jpg",
          "Address": "84GQ+HXM, Jl. Jenderal Sudirman, Dasan Geres, Kec. Gerung, Kabupaten Lombok Barat, Nusa Tenggara Bar. 83363, Indonesia",
          "ContactNo": "",
          "WebsiteUrl": "",
          "Longitude": "116.13989174365997",
          "Langitude": "-8.673431247098552",
          "CategoryName": "Home & Garden",
          "SubCategoryName": "Lawn & Garden    ",
          "Name": "TANAH KAVELING COCOK BUAT RUMAH PRIBADI DAN KIOS",
          "Currency": "",
          "MinPrice": "75",
          "MaxPrice": "",
          "DiscountPrice": "75",
          "Weight": "",
          "DeliveryCharge": "0",
          "Description": "DI JUAL TANAH KAVELING DENGAN HARGA 75JUTA 1 ARE (100M²) LOKASI DASAN GERES KOTA GERUNG LOMBOK BARAT DEKAT KANTOR BUPATI GERUNG DAN BUNDARAN TUGU SEGITIGA GERUNG LOMBOK BARAT\nLENGKAP FASILITAS SUDAH TERIMA PEMECAHAN SERTIFIKAT ATAS NAMA PEMBELI",
          "Condition": "",
          "Images": "[{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1661552631160.jpg\"},{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1661552638882.jpg\"},{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1661552642818.jpg\"},{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1661552646305.jpg\"},{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1661552650317.jpg\"}]",
          "Negotiation": "false",
          "SoldStatus": "Unsold",
          "ProductType": "",
          "UserSince": "August 2022",
          "CreatAt": "27-08-2022",
          "ProductSave": "1",
          "ProductReport": "1",
          "AverageRating": "0",
          "TotalUser": "0"
        },
        {
          "Id": "198",
          "UserId": "2651",
          "UserName": "Ikrima  Hasyima ",
          "UserProfile": "https://s3.us-east-2.amazonaws.com/inunion/1662953393900.jpg",
          "Address": "QV54+R4V, Jl. Kp. Tim., Gn. Samarinda, Kec. Balikpapan Utara, Kota Balikpapan, Kalimantan Timur 76124, Indonesia",
          "ContactNo": "",
          "WebsiteUrl": "",
          "Longitude": "116.85508400201799",
          "Langitude": "-1.2403925810773377",
          "CategoryName": "Skin Care & Beauty",
          "SubCategoryName": "Cosmetics   ",
          "Name": "rose glow by MAHVEEN skincare ",
          "Currency": "",
          "MinPrice": "120",
          "MaxPrice": "",
          "DiscountPrice": "120",
          "Weight": "",
          "DeliveryCharge": "0",
          "Description": "Rose Glow Essence ini fungsi utamanya untuk hidrasi (melembabkan) kulit wajah dan juga sebagai anti pollutan (polusi) yang bisa menangkal radikal bebas. \nAplikasinya untuk kulit normal cenderung kering.",
          "Condition": "",
          "Images": "[{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1661560088117.jpg\"},{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1661560093033.jpg\"}]",
          "Negotiation": "false",
          "SoldStatus": "Unsold",
          "ProductType": "",
          "UserSince": "August 2022",
          "CreatAt": "27-08-2022",
          "ProductSave": "1",
          "ProductReport": "1",
          "AverageRating": "4.8",
          "TotalUser": "2"
        },
        {
          "Id": "199",
          "UserId": "2651",
          "UserName": "Ikrima  Hasyima ",
          "UserProfile": "https://s3.us-east-2.amazonaws.com/inunion/1662953393900.jpg",
          "Address": "QV54+R4V, Jl. Kp. Tim., Gn. Samarinda, Kec. Balikpapan Utara, Kota Balikpapan, Kalimantan Timur 76124, Indonesia",
          "ContactNo": "",
          "WebsiteUrl": "",
          "Longitude": "116.85508400201799",
          "Langitude": "-1.2403925810773377",
          "CategoryName": "Skin Care & Beauty",
          "SubCategoryName": "Cosmetics   ",
          "Name": "mahveen skincare  produk skincare terbaik muslimah ",
          "Currency": "",
          "MinPrice": "268",
          "MaxPrice": "",
          "DiscountPrice": "268",
          "Weight": "",
          "DeliveryCharge": "0",
          "Description": "\nmanfaat kan promo akhir pekan yuk\ndengan pembelian 2 paket mahveen mendapatkan deef cleansing  water senilai 85 ribu\nberlaku kelipatan ya Shalihah\n\nmahveen skincare solusi wajah flek hitam  mu",
          "Condition": "",
          "Images": "[{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1661560373516.jpg\"}]",
          "Negotiation": "false",
          "SoldStatus": "Unsold",
          "ProductType": "",
          "UserSince": "August 2022",
          "CreatAt": "27-08-2022",
          "ProductSave": "1",
          "ProductReport": "1",
          "AverageRating": "0",
          "TotalUser": "0"
        },
        {
          "Id": "200",
          "UserId": "1511",
          "UserName": "Indah EN-Nury EN-Nury",
          "UserProfile": "https://s3.us-east-2.amazonaws.com/inunion/1669379570348.jpg",
          "Address": "39F2+J3H, Asem, Payaman, Kec. Solokuro, Kabupaten Lamongan, Jawa Timur 62265, Indonesia",
          "ContactNo": "",
          "WebsiteUrl": "",
          "Longitude": "112.3508644849062",
          "Langitude": "-6.926244456610084",
          "CategoryName": "Skin Care & Beauty",
          "SubCategoryName": "Other    ",
          "Name": "Habbasi cold press (minyak hitam) ",
          "Currency": "",
          "MinPrice": "20",
          "MaxPrice": "",
          "DiscountPrice": "20",
          "Weight": "",
          "DeliveryCharge": "0",
          "Description": "obat segala penyakit",
          "Condition": "",
          "Images": "[{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1661562072786.jpg\"}]",
          "Negotiation": "false",
          "SoldStatus": "Unsold",
          "ProductType": "",
          "UserSince": "August 2022",
          "CreatAt": "27-08-2022",
          "ProductSave": "1",
          "ProductReport": "1",
          "AverageRating": "4.5",
          "TotalUser": "1"
        },
        {
          "Id": "201",
          "UserId": "2642",
          "UserName": "Abu ZUBAIR",
          "UserProfile": "https://s3.us-east-2.amazonaws.com/inunion/1661407163433.jpg",
          "Address": "Jl. Ps. Palabuhanratu, Pelabuhanratu, Kec. Pelabuhanratu, Kabupaten Sukabumi, Jawa Barat, Indonesia",
          "ContactNo": "",
          "WebsiteUrl": "",
          "Longitude": "106.5451892",
          "Langitude": "-6.9854078",
          "CategoryName": "Hobbies",
          "SubCategoryName": "Other    ",
          "Name": "keripik tempe",
          "Currency": "rupiah",
          "MinPrice": "1234",
          "MaxPrice": "",
          "DiscountPrice": "0",
          "Weight": "",
          "DeliveryCharge": "0",
          "Description": "bersih, renyah, gurih InsyaAllah halal",
          "Condition": "",
          "Images": "[{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1661564543985.jpg\"},{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1661564548160.jpg\"},{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1661564549227.jpg\"},{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1661564550009.jpg\"}]",
          "Negotiation": "false",
          "SoldStatus": "Unsold",
          "ProductType": "",
          "UserSince": "August 2022",
          "CreatAt": "27-08-2022",
          "ProductSave": "1",
          "ProductReport": "1",
          "AverageRating": "5",
          "TotalUser": "1"
        },
        {
          "Id": "202",
          "UserId": "2508",
          "UserName": "Muhammad Wahyudin",
          "UserProfile": "https://s3.us-east-2.amazonaws.com/inunion/1661420642333.jpg",
          "Address": "Bandung, Kota Bandung, Jawa Barat, Indonesia",
          "ContactNo": "",
          "WebsiteUrl": "",
          "Longitude": "107.6191228",
          "Langitude": "-6.9174639",
          "CategoryName": "Clothing & Jewelry",
          "SubCategoryName": "Men Shoes    ",
          "Name": "sneakers",
          "Currency": "",
          "MinPrice": "14.7",
          "MaxPrice": "",
          "DiscountPrice": "14.7",
          "Weight": "",
          "DeliveryCharge": "0",
          "Description": "Cerah, Fleksibel. dan ke depan. Sepatu NAZ DISTRO yang dirancang secara khusus untuk memberikan rasa nyaman sepanjang hari, sehingga kamu bisa menggunakannya kapanpun dan dimanapun",
          "Condition": "",
          "Images": "[{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1661579464633.jpg\"},{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1661579478966.jpg\"},{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1661579487043.jpg\"},{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1661579494938.jpg\"},{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1661579503128.jpg\"}]",
          "Negotiation": "false",
          "SoldStatus": "Unsold",
          "ProductType": "",
          "UserSince": "August 2022",
          "CreatAt": "27-08-2022",
          "ProductSave": "1",
          "ProductReport": "1",
          "AverageRating": "0",
          "TotalUser": "0"
        },
        {
          "Id": "203",
          "UserId": "2651",
          "UserName": "Ikrima  Hasyima ",
          "UserProfile": "https://s3.us-east-2.amazonaws.com/inunion/1662953393900.jpg",
          "Address": "QV54+R4V, Jl. Kp. Tim., Gn. Samarinda, Kec. Balikpapan Utara, Kota Balikpapan, Kalimantan Timur 76124, Indonesia",
          "ContactNo": "",
          "WebsiteUrl": "",
          "Longitude": "116.85508500784636",
          "Langitude": "-1.2403932514724652",
          "CategoryName": "Skin Care & Beauty",
          "SubCategoryName": "Cosmetics   ",
          "Name": "MAHVEEN SKINCARE ",
          "Currency": "",
          "MinPrice": "268",
          "MaxPrice": "",
          "DiscountPrice": "268",
          "Weight": "",
          "DeliveryCharge": "0",
          "Description": "Mahveen termasuk dalam golongan kosmetik, namun kosmetik sendiri dibagi lagi menjadi beberapa golongan. Salah satunya adalah skincare, dimana kosmetik golongan skincare  cirinya adalah memilihi bahan aktif untuk target tertentu yang berfungsi untuk merawat kulit, tujuannya untuk perawatan kulit jangka panjang, seperti untuk mencerahkan, anti aging, membantu dan mengontrol kulit berjerawat, dlsb.\n\nAdapun kosmetik yang bersifat untuk make up dinamakan kosmetik golongan dekoratif, ia hanya memberikan efek make up instan dan tidak mengandung bahan bahan aktif untuk perawatan kulit.",
          "Condition": "",
          "Images": "[{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1661585174543.jpg\"},{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1661585190139.jpg\"}]",
          "Negotiation": "false",
          "SoldStatus": "Unsold",
          "ProductType": "",
          "UserSince": "August 2022",
          "CreatAt": "27-08-2022",
          "ProductSave": "1",
          "ProductReport": "1",
          "AverageRating": "0",
          "TotalUser": "0"
        },
        {
          "Id": "204",
          "UserId": "2651",
          "UserName": "Ikrima  Hasyima ",
          "UserProfile": "https://s3.us-east-2.amazonaws.com/inunion/1662953393900.jpg",
          "Address": "QV54+R4V, Jl. Kp. Tim., Gn. Samarinda, Kec. Balikpapan Utara, Kota Balikpapan, Kalimantan Timur 76124, Indonesia",
          "ContactNo": "",
          "WebsiteUrl": "",
          "Longitude": "116.85508467257023",
          "Langitude": "-1.2403925810773377",
          "CategoryName": "Skin Care & Beauty",
          "SubCategoryName": "Cosmetics   ",
          "Name": "mahveen skincare muslimah",
          "Currency": "",
          "MinPrice": "268",
          "MaxPrice": "",
          "DiscountPrice": "268",
          "Weight": "",
          "DeliveryCharge": "0",
          "Description": " mahveen skincare  skincare yang  banyak di minati oleh para wanita muslimah karena mahveen adalah skincare terbaik dengan komposisi bahan terbaik bisa di cek di google mahven store ya\nkehalalan dan izin BPOM nya",
          "Condition": "",
          "Images": "[{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1661585775023.jpg\"},{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1661585778547.jpg\"}]",
          "Negotiation": "false",
          "SoldStatus": "Unsold",
          "ProductType": "",
          "UserSince": "August 2022",
          "CreatAt": "27-08-2022",
          "ProductSave": "1",
          "ProductReport": "1",
          "AverageRating": "0",
          "TotalUser": "0"
        },
        {
          "Id": "205",
          "UserId": "2620",
          "UserName": "Muhammad Harfandi",
          "UserProfile": "https://s3.us-east-2.amazonaws.com/inunion/1663219915198.jpg",
          "Address": "84HQ+M23, Jl. Mahoni II, Dasan Geres, Kec. Gerung, Kabupaten Lombok Barat, Nusa Tenggara Bar. 83363, Indonesia",
          "ContactNo": "",
          "WebsiteUrl": "",
          "Longitude": "116.13721758127213",
          "Langitude": "-8.67020597228963",
          "CategoryName": "Home & Garden",
          "SubCategoryName": "Lawn & Garden    ",
          "Name": "TANAH KAVELING",
          "Currency": "",
          "MinPrice": "75",
          "MaxPrice": "",
          "DiscountPrice": "22",
          "Weight": "",
          "DeliveryCharge": "0",
          "Description": "Promo terdahsyat bulan ini\n1. Cashback uang booking fee 100% \n2. Diskon sampai dengan 25 juta per are\n3. Uang Dp 50% bisa dicicil dua kali dengan skema 25% : 25%\n4. Tanpa bunga skema cicilan mudah dan meriah buruan mumpung belum kehabisan lokasi tanah kavling sangat strategis kemana-mana serba dekat harga terjangkau hanya 75jt/are bisa beli 1 are, 2 are, 3 are dan seterusnya\n\nBerminat WA di 087752421465",
          "Condition": "",
          "Images": "[{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1661593292456.jpg\"},{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1661593298170.jpg\"},{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1661593299333.jpg\"},{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1661593301033.jpg\"},{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1661593302171.jpg\"}]",
          "Negotiation": "false",
          "SoldStatus": "Unsold",
          "ProductType": "",
          "UserSince": "August 2022",
          "CreatAt": "27-08-2022",
          "ProductSave": "1",
          "ProductReport": "1",
          "AverageRating": "0",
          "TotalUser": "0"
        },
        {
          "Id": "206",
          "UserId": "2896",
          "UserName": "BAYU RIYADH",
          "UserProfile": "https://s3.us-east-2.amazonaws.com/inunion/1661599832697.jpg",
          "Address": "QP6V+JJH, Al Quds, Riyadh 13214, Arab Saudi",
          "ContactNo": "",
          "WebsiteUrl": "",
          "Longitude": "46.74414128065109",
          "Langitude": "24.761567875160814",
          "CategoryName": "Family",
          "SubCategoryName": "Other    ",
          "Name": "massage+bekam hijjamah",
          "Currency": "",
          "MinPrice": "250",
          "MaxPrice": "",
          "DiscountPrice": "200",
          "Weight": "",
          "DeliveryCharge": "0",
          "Description": "swidis,thaylandi,shiatsu. ",
          "Condition": "",
          "Images": "[{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1661600781329.jpg\"},{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1661600788440.jpg\"}]",
          "Negotiation": "false",
          "SoldStatus": "Unsold",
          "ProductType": "",
          "UserSince": "August 2022",
          "CreatAt": "27-08-2022",
          "ProductSave": "1",
          "ProductReport": "1",
          "AverageRating": "5",
          "TotalUser": "1"
        },
        {
          "Id": "207",
          "UserId": "2522",
          "UserName": "Ilwansyah Cahyono",
          "UserProfile": "https://s3.us-east-2.amazonaws.com/inunion/1661476578554.jpg",
          "Address": "5, Jl. Bambu Kuning I No.17, RT.5/RW.8, Rawamangun, Kec. Pulo Gadung, Kota Jakarta Timur, Daerah Khusus Ibukota Jakarta 13220, Indonesia",
          "ContactNo": "",
          "WebsiteUrl": "",
          "Longitude": "106.88874296844006",
          "Langitude": "-6.198541278380698",
          "CategoryName": "Skin Care & Beauty",
          "SubCategoryName": "Other    ",
          "Name": "Jahe merah plus Haubatsaudah madu Gingseng Jahe ",
          "Currency": "",
          "MinPrice": "5",
          "MaxPrice": "",
          "DiscountPrice": "4.5",
          "Weight": "",
          "DeliveryCharge": "0",
          "Description": "Jahe merah baik untuk kesehatan melancarkan peredaran darah anti deman gejala Corona.",
          "Condition": "",
          "Images": "[{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1661607329317.jpg\"},{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1661607334308.jpg\"}]",
          "Negotiation": "false",
          "SoldStatus": "Unsold",
          "ProductType": "",
          "UserSince": "August 2022",
          "CreatAt": "27-08-2022",
          "ProductSave": "1",
          "ProductReport": "1",
          "AverageRating": "0",
          "TotalUser": "0"
        },
        {
          "Id": "208",
          "UserId": "2620",
          "UserName": "Muhammad Harfandi",
          "UserProfile": "https://s3.us-east-2.amazonaws.com/inunion/1663219915198.jpg",
          "Address": "Jl. Langko No.112, Dasan Agung Baru, Kec. Selaparang, Kota Mataram, Nusa Tenggara Bar. 83113, Indonesia",
          "ContactNo": "",
          "WebsiteUrl": "",
          "Longitude": "116.09161701053381",
          "Langitude": "-8.578742651235633",
          "CategoryName": "Home & Garden",
          "SubCategoryName": "Lawn & Garden    ",
          "Name": "RUMAH BESAR AND DESAIGN MEWAH",
          "Currency": "",
          "MinPrice": "650",
          "MaxPrice": "",
          "DiscountPrice": "25",
          "Weight": "",
          "DeliveryCharge": "0",
          "Description": "Di jual rumah dgn Spesifikasi sbb :\n\nKamar Tidur 3\nKamar Mandi 4\nGarasi \nDapur\nRuang keluarga\nRuang tamu\nSecurity 24 jam\nOne Gate sistem\n\nOpen harga 650jt/nego\n\njln. Ade Irma Suryani\nPerumahan Griya Pesona  Monjok, Monjok Timur Mataram\n\nBerminat WA : 087770433257",
          "Condition": "",
          "Images": "[{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1661608394781.jpg\"},{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1661608399523.jpg\"},{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1661608400451.jpg\"},{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1661608401465.jpg\"},{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1661608402574.jpg\"}]",
          "Negotiation": "false",
          "SoldStatus": "Unsold",
          "ProductType": "",
          "UserSince": "August 2022",
          "CreatAt": "27-08-2022",
          "ProductSave": "1",
          "ProductReport": "1",
          "AverageRating": "0",
          "TotalUser": "0"
        },
        {
          "Id": "183",
          "UserId": "2620",
          "UserName": "Muhammad Harfandi",
          "UserProfile": "https://s3.us-east-2.amazonaws.com/inunion/1663219915198.jpg",
          "Address": "Jl. Raya Sembada Asri Blk. F No.23, Kekalik Jaya, Kec. Mataram, Kota Mataram, Nusa Tenggara Bar. 83115, Indonesia",
          "ContactNo": "",
          "WebsiteUrl": "",
          "Longitude": "116.09146647155286",
          "Langitude": "-8.591624830632652",
          "CategoryName": "Real Estate",
          "SubCategoryName": "Sale     ",
          "Name": "DI JUAL RUMAH HARGA MURAH 400 JUTA",
          "Currency": "",
          "MinPrice": "400",
          "MaxPrice": "",
          "DiscountPrice": "400",
          "Weight": "",
          "DeliveryCharge": "0",
          "Description": "Buka harga Rp. 400 juta\n\nDi jual RUMAH\n- Luas Tanah 1 are Lante 2\n- 3 Kamar tidur\n- 2 kamar mandi\n- Teras\n- Garasi\n- Dapur\n- Ruang Tamu\n- Ruang Keluarga\n- Akses Jalan Lebar 7 meter lebih bisa papasan 2 Mobil\nLokasi depan Kampus Unram atau RS Unram Kota Mataram Lombok Indonesia tepatnya di Jl. Griya Sembada Asri\n\nTanya² di WA 087752421465",
          "Condition": "",
          "Images": "[{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1661467636209.jpg\"}]",
          "Negotiation": "false",
          "SoldStatus": "Unsold",
          "ProductType": "",
          "UserSince": "August 2022",
          "CreatAt": "26-08-2022",
          "ProductSave": "1",
          "ProductReport": "1",
          "AverageRating": "0",
          "TotalUser": "0"
        },
        {
          "Id": "185",
          "UserId": "2684",
          "UserName": "Ami",
          "UserProfile": "https://s3.us-east-2.amazonaws.com/inunion/1661470233951.jpg",
          "Address": "RCCA6983، 6983 الشطرة، 3091، حي سكيرينة، Riyadh 12654, Arab Saudi",
          "ContactNo": "",
          "WebsiteUrl": "",
          "Longitude": "46.71657655388117",
          "Langitude": "24.613414579967387",
          "CategoryName": "Skin Care & Beauty",
          "SubCategoryName": "Skin Care    ",
          "Name": "perawatan kulit ",
          "Currency": "sr",
          "MinPrice": "30",
          "MaxPrice": "",
          "DiscountPrice": "25",
          "Weight": "",
          "DeliveryCharge": "0",
          "Description": "yang butuh alat mandi dan kecantikan silahkan inbok disini tersedia pesan antar harga sesuai product untuk harga ongkir tergantung lokasi .",
          "Condition": "",
          "Images": "[{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1661468386312.jpg\"}]",
          "Negotiation": "false",
          "SoldStatus": "Unsold",
          "ProductType": "",
          "UserSince": "August 2022",
          "CreatAt": "26-08-2022",
          "ProductSave": "1",
          "ProductReport": "1",
          "AverageRating": "0",
          "TotalUser": "0"
        },
        {
          "Id": "186",
          "UserId": "2684",
          "UserName": "Ami",
          "UserProfile": "https://s3.us-east-2.amazonaws.com/inunion/1661470233951.jpg",
          "Address": "RCCA7131، 7131 سليط العامري، 3193، حي سكيرينة، Riyadh 12654, Arab Saudi",
          "ContactNo": "",
          "WebsiteUrl": "",
          "Longitude": "46.71761121600866",
          "Langitude": "24.614767330418097",
          "CategoryName": "Clothing & Jewelry",
          "SubCategoryName": "Women Clothing    ",
          "Name": "Uniform Riyadh ",
          "Currency": "sr",
          "MinPrice": "30",
          "MaxPrice": "",
          "DiscountPrice": "25",
          "Weight": "",
          "DeliveryCharge": "0",
          "Description": "yang minat uniform silahkan. semua warna dan ukuran tersedia \nS, M, L, 65sr\nuntuk harga kiriman di bawah ini \n",
          "Condition": "",
          "Images": "[{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1661473141267.jpg\"},{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1661473145394.jpg\"},{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1661473147590.jpg\"}]",
          "Negotiation": "false",
          "SoldStatus": "Unsold",
          "ProductType": "",
          "UserSince": "August 2022",
          "CreatAt": "26-08-2022",
          "ProductSave": "1",
          "ProductReport": "1",
          "AverageRating": "0",
          "TotalUser": "0"
        },
        {
          "Id": "188",
          "UserId": "2522",
          "UserName": "Ilwansyah Cahyono",
          "UserProfile": "https://s3.us-east-2.amazonaws.com/inunion/1661476578554.jpg",
          "Address": "5, Jl. Bambu Kuning I No.17, RT.5/RW.8, Rawamangun, Kec. Pulo Gadung, Kota Jakarta Timur, Daerah Khusus Ibukota Jakarta 13220, Indonesia",
          "ContactNo": "",
          "WebsiteUrl": "",
          "Longitude": "106.88874565064907",
          "Langitude": "-6.1985379452206235",
          "CategoryName": "Skin Care & Beauty",
          "SubCategoryName": "Skin Care    ",
          "Name": "Damar bubuk ",
          "Currency": "",
          "MinPrice": "5",
          "MaxPrice": "",
          "DiscountPrice": "4.5",
          "Weight": "",
          "DeliveryCharge": "0",
          "Description": "Bubuk getah pohon Damar Lampung amat baik untuk bahan baku bedak pengharum tubuh dan pembersih wajah serta menghaluskan wajah mebasmi anti jerawat pada kulit wajah wanita & pria juga baik untuk bayi dan anak².",
          "Condition": "",
          "Images": "[{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1661477191589.jpg\"},{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1661477195373.jpg\"}]",
          "Negotiation": "false",
          "SoldStatus": "Unsold",
          "ProductType": "",
          "UserSince": "August 2022",
          "CreatAt": "26-08-2022",
          "ProductSave": "1",
          "ProductReport": "1",
          "AverageRating": "0",
          "TotalUser": "0"
        },
        {
          "Id": "191",
          "UserId": "2454",
          "UserName": "Izharyono",
          "UserProfile": "",
          "Address": "Jalan Tanpa Nama, Peradong, Kec. Simpang Teritip, Kabupaten Bangka Barat, Kepulauan Bangka Belitung 33366, Indonesia",
          "ContactNo": "",
          "WebsiteUrl": "",
          "Longitude": "105.38169488310814",
          "Langitude": "-1.8851698943242083",
          "CategoryName": "Family",
          "SubCategoryName": "Other    ",
          "Name": "Rusip",
          "Currency": "",
          "MinPrice": "10",
          "MaxPrice": "",
          "DiscountPrice": "10",
          "Weight": "",
          "DeliveryCharge": "0",
          "Description": "Makanan khas Bangka \nbahan baku ikan tri di permentasi",
          "Condition": "",
          "Images": "[{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1661525242529.jpg\"}]",
          "Negotiation": "false",
          "SoldStatus": "Unsold",
          "ProductType": "",
          "UserSince": "August 2022",
          "CreatAt": "26-08-2022",
          "ProductSave": "1",
          "ProductReport": "1",
          "AverageRating": "5",
          "TotalUser": "1"
        },
        {
          "Id": "78",
          "UserId": "220",
          "UserName": "Luqman Hakim Noegroho Putro",
          "UserProfile": "",
          "Address": "J444+WX4, Sukaragam, Serang Baru, Bekasi Regency, West Java 17330, Indonesia",
          "ContactNo": "",
          "WebsiteUrl": "",
          "Longitude": "107.1074445",
          "Langitude": "-6.392746000000001",
          "CategoryName": "Home & Garden",
          "SubCategoryName": "Other    ",
          "Name": "Coconut charcoal briquettes",
          "Currency": "",
          "MinPrice": "1.37",
          "MaxPrice": "",
          "DiscountPrice": "1.37",
          "Weight": "",
          "DeliveryCharge": "0",
          "Description": "Premium Quality\nSpecific:\n- Moisture max. 8%\n- Ash. max. 3%\n- Volatile Matter max. 17%\n- Fixed Carbon. min. 75%\n- Calori Value 7.000 kilo calori\n\nKeunggulan Areng briket / Advantages of Charcoal briquettes:\n - durable / tahan lama\n - smokeless / tanpa asap\n - Environmentally friendly\n - Natural / Chemical free",
          "Condition": "",
          "Images": "[{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1653538531278.jpg\"},{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1653538536127.jpg\"},{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1653538537012.jpg\"},{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1653538545074.jpg\"}]",
          "Negotiation": "false",
          "SoldStatus": "Unsold",
          "ProductType": "",
          "UserSince": "May 2022",
          "CreatAt": "26-05-2022",
          "ProductSave": "1",
          "ProductReport": "1",
          "AverageRating": "5",
          "TotalUser": "3"
        },
        {
          "Id": "79",
          "UserId": "221",
          "UserName": "Erisa Mirza Lina Siregar",
          "UserProfile": "https://s3.us-east-2.amazonaws.com/inunion/1653559907963.jpg",
          "Address": "Jl. Karang Anyar 1, Loktabat Utara, Kec. Banjarbaru Utara, Kota Banjar Baru, Kalimantan Selatan 70714, Indonesia",
          "ContactNo": "",
          "WebsiteUrl": "",
          "Longitude": "114.81927",
          "Langitude": "-3.434727499999999",
          "CategoryName": "Hobbies",
          "SubCategoryName": "Other    ",
          "Name": "mushaf al mubtadi",
          "Currency": "",
          "MinPrice": "7",
          "MaxPrice": "",
          "DiscountPrice": "7",
          "Weight": "",
          "DeliveryCharge": "0",
          "Description": "mushaf tanpa terjemahan dengan wakaf dan ibtida",
          "Condition": "",
          "Images": "[{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1653560238386.jpg\"},{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1653560242213.jpg\"}]",
          "Negotiation": "false",
          "SoldStatus": "Unsold",
          "ProductType": "",
          "UserSince": "May 2022",
          "CreatAt": "26-05-2022",
          "ProductSave": "1",
          "ProductReport": "1",
          "AverageRating": "4",
          "TotalUser": "4"
        },
        {
          "Id": "363",
          "UserId": "3756",
          "UserName": "Thony S",
          "UserProfile": "https://s3.us-east-2.amazonaws.com/inunion/1666421937323.jpg",
          "Address": "3090, Al Jamiah, Medina 42351, Saudi Arabia",
          "ContactNo": "",
          "WebsiteUrl": "",
          "Longitude": "",
          "Langitude": "",
          "CategoryName": "Electronics",
          "SubCategoryName": "Other ",
          "Name": "Smartwatch Amazfit GTS 2 mini",
          "Currency": "SAR",
          "MinPrice": "260",
          "MaxPrice": "",
          "DiscountPrice": "259",
          "Weight": "",
          "DeliveryCharge": "0",
          "Description": "smartwatch Amazfit GTS 2 mini , fullset , nominus , pemakaian 2 bulan , minat hubungi via wa +966592639305",
          "Condition": "",
          "Images": "[{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1671953506264.jpg\"},{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1671953510197.jpg\"},{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1671953513018.jpg\"},{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1671953514587.jpg\"}]",
          "Negotiation": "false",
          "SoldStatus": "Unsold",
          "ProductType": "",
          "UserSince": "October 2022",
          "CreatAt": "25-12-2022",
          "ProductSave": "1",
          "ProductReport": "1",
          "AverageRating": "0",
          "TotalUser": "0"
        },
        {
          "Id": "321",
          "UserId": "3584",
          "UserName": "Muhammad Dimas",
          "UserProfile": "https://s3.us-east-2.amazonaws.com/inunion/1664100009262.jpg",
          "Address": "JASA2203, 2203 Hassan Abdullah Al Ash Shaykh, 8273, As Sulaymaniyah District, Jeddah 22253, Arab Saudi",
          "ContactNo": "",
          "WebsiteUrl": "",
          "Longitude": "39.24102298915386",
          "Langitude": "21.504290935723795",
          "CategoryName": "Vehicles",
          "SubCategoryName": "Cars    ",
          "Name": "XTRAIL NISSAN TAHUN 2002",
          "Currency": "",
          "MinPrice": "28000",
          "MaxPrice": "",
          "DiscountPrice": "28000",
          "Weight": "",
          "DeliveryCharge": "0",
          "Description": "stnk mati 4 tahun dan selebihnya cek sendiri keadaan mobilnya dilepas 8000 real aja",
          "Condition": "",
          "Images": "[{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1664100858891.jpg\"},{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1664100860582.jpg\"},{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1664100861438.jpg\"}]",
          "Negotiation": "false",
          "SoldStatus": "Unsold",
          "ProductType": "",
          "UserSince": "September 2022",
          "CreatAt": "25-09-2022",
          "ProductSave": "1",
          "ProductReport": "1",
          "AverageRating": "5",
          "TotalUser": "1"
        },
        {
          "Id": "163",
          "UserId": "2620",
          "UserName": "Muhammad Harfandi",
          "UserProfile": "https://s3.us-east-2.amazonaws.com/inunion/1663219915198.jpg",
          "Address": "JL. Panjitilar Negara, Mataram, 83115, Kekalik Jaya, Sekarbela, Mataram City, West Nusa Tenggara 83115, Indonesia",
          "ContactNo": "",
          "WebsiteUrl": "",
          "Longitude": "116.08548883348702",
          "Langitude": "-8.590707862533488",
          "CategoryName": "Home & Garden",
          "SubCategoryName": "Furniture    ",
          "Name": "JUAL RUMAH DALAM KOTA MATARAM LOMBOK",
          "Currency": "",
          "MinPrice": "460",
          "MaxPrice": "",
          "DiscountPrice": "460",
          "Weight": "",
          "DeliveryCharge": "0",
          "Description": "Di Jual Rumah Lokasi Jl. Serayu BTN Kekalik\nLuas Tanah 120m2\nBuka harga 460jt/nego tipis-tipis",
          "Condition": "",
          "Images": "[{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1661380958865.jpg\"},{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1661380962988.jpg\"},{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1661380964011.jpg\"},{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1661380965345.jpg\"},{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1661380966447.jpg\"}]",
          "Negotiation": "false",
          "SoldStatus": "Unsold",
          "ProductType": "",
          "UserSince": "August 2022",
          "CreatAt": "25-08-2022",
          "ProductSave": "1",
          "ProductReport": "1",
          "AverageRating": "0",
          "TotalUser": "0"
        },
        {
          "Id": "165",
          "UserId": "2620",
          "UserName": "Muhammad Harfandi",
          "UserProfile": "https://s3.us-east-2.amazonaws.com/inunion/1663219915198.jpg",
          "Address": "Lingkar Permata Residance Blok A4, Jl. Lingkar Selatan No.99, Pagutan, Kec. Mataram, Kota Mataram, Nusa Tenggara Bar. 83361, Indonesia",
          "ContactNo": "",
          "WebsiteUrl": "",
          "Longitude": "116.0999144241214",
          "Langitude": "-8.617261577863195",
          "CategoryName": "Real Estate",
          "SubCategoryName": "Other    ",
          "Name": "RUMAH DI JUAL",
          "Currency": "",
          "MinPrice": "750",
          "MaxPrice": "",
          "DiscountPrice": "750",
          "Weight": "",
          "DeliveryCharge": "0",
          "Description": "Di jual rumah Lokasi di Perumahan Grand Lingkar Cluster Andalusia Blok CH 09, Jempong Kota Mataram Lombok Indonesia",
          "Condition": "",
          "Images": "[{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1661398605267.jpg\"},{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1661398610115.jpg\"},{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1661398611136.jpg\"},{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1661398612021.jpg\"},{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1661398613000.jpg\"}]",
          "Negotiation": "false",
          "SoldStatus": "Unsold",
          "ProductType": "",
          "UserSince": "August 2022",
          "CreatAt": "25-08-2022",
          "ProductSave": "1",
          "ProductReport": "1",
          "AverageRating": "0",
          "TotalUser": "0"
        },
        {
          "Id": "166",
          "UserId": "2620",
          "UserName": "Muhammad Harfandi",
          "UserProfile": "https://s3.us-east-2.amazonaws.com/inunion/1663219915198.jpg",
          "Address": "Jl. Amir Hamzah No.11, Mataram Tim., Kec. Mataram, Kota Mataram, Nusa Tenggara Bar. 83127, Indonesia",
          "ContactNo": "",
          "WebsiteUrl": "",
          "Longitude": "116.11249297857286",
          "Langitude": "-8.588083584385133",
          "CategoryName": "Home & Garden",
          "SubCategoryName": "Furniture    ",
          "Name": "for Sale Home (rumah dijual) murah dalam kota",
          "Currency": "",
          "MinPrice": "620",
          "MaxPrice": "",
          "DiscountPrice": "620",
          "Weight": "",
          "DeliveryCharge": "0",
          "Description": "Ada Rumah mau di Jl. AMIR HAMZAH Karang Sukun sekomplek dengan rumah walikota Mataram murah dikasih pemilik rumah lagi butuh dana... Pinggir jalan Aspal jl. Amir Hamzah Karang Sukun Kota Mataram Lombok bisa buat toko atau ruko didepannya buka harga 620jt nego bisa di Dp atau dicicil sisanya... Luas tanah 175m² Barat SMK atau Universitas Saraswati Kota Mataram Lombok Lebar jalannya 6 meter",
          "Condition": "",
          "Images": "[{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1661401035597.jpg\"},{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1661401038673.jpg\"},{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1661401039854.jpg\"}]",
          "Negotiation": "false",
          "SoldStatus": "Unsold",
          "ProductType": "",
          "UserSince": "August 2022",
          "CreatAt": "25-08-2022",
          "ProductSave": "1",
          "ProductReport": "1",
          "AverageRating": "0",
          "TotalUser": "0"
        },
        {
          "Id": "168",
          "UserId": "2556",
          "UserName": "Nurdi",
          "UserProfile": "https://s3.us-east-2.amazonaws.com/inunion/1661269976670.jpg",
          "Address": "Jl. Tangkil Gede No.35, Pasalakan, Kec. Sumber, Kabupaten Cirebon, Jawa Barat 45611, Indonesia",
          "ContactNo": "",
          "WebsiteUrl": "",
          "Longitude": "108.49349319934845",
          "Langitude": "-6.73293287848478",
          "CategoryName": "Clothing & Jewelry",
          "SubCategoryName": "Men Clothing    ",
          "Name": "Uhud is Good",
          "Currency": "",
          "MinPrice": "179000",
          "MaxPrice": "",
          "DiscountPrice": "179000",
          "Weight": "",
          "DeliveryCharge": "0",
          "Description": "UHUD BASIC ®\n▶️ Uhud is Good\n▶️ Modern\n▶️ Model Up to Date\n▶️ Confident\n▶️ Good quality\n °°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°\nBERKUALITAS DAN BAGUS\n\n⏭️ FABRIC TYPE  :   OXFORFD SLUB\n⏭️ SIZE    :  M L XL \n⏭️ PRICE : 179.000 ",
          "Condition": "",
          "Images": "[{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1661405903711.jpg\"},{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1661405908840.jpg\"},{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1661405909441.jpg\"},{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1661405909984.jpg\"}]",
          "Negotiation": "false",
          "SoldStatus": "Unsold",
          "ProductType": "",
          "UserSince": "August 2022",
          "CreatAt": "25-08-2022",
          "ProductSave": "1",
          "ProductReport": "1",
          "AverageRating": "0",
          "TotalUser": "0"
        },
        {
          "Id": "169",
          "UserId": "2556",
          "UserName": "Nurdi",
          "UserProfile": "https://s3.us-east-2.amazonaws.com/inunion/1661269976670.jpg",
          "Address": "7F8V+P87 Asrama H. Cirebon, Jl. Tangkil Gede, Watubelah, Kec. Sumber, Kabupaten Cirebon, Jawa Barat 45611, Indonesia",
          "ContactNo": "",
          "WebsiteUrl": "",
          "Longitude": "108.49323939532042",
          "Langitude": "-6.732942867400777",
          "CategoryName": "Clothing & Jewelry",
          "SubCategoryName": "Men Clothing    ",
          "Name": "Uhud is Good",
          "Currency": "",
          "MinPrice": "199",
          "MaxPrice": "",
          "DiscountPrice": "199",
          "Weight": "",
          "DeliveryCharge": "0",
          "Description": "BERKUALITAS DAN BAGUS\n\n⏭️ FABRIC TYPE  : COTTON TWILL STRECH \n⏭️ SIZE    : S M L XL ",
          "Condition": "",
          "Images": "[{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1661406350554.jpg\"},{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1661406354284.jpg\"},{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1661406354938.jpg\"},{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1661406355592.jpg\"},{\"url\":\"https://s3.us-east-2.amazonaws.com/inunion/1661406356323.jpg\"}]",
          "Negotiation": "false",
          "SoldStatus": "Unsold",
          "ProductType": "",
          "UserSince": "August 2022",
          "CreatAt": "25-08-2022",
          "ProductSave": "1",
          "ProductReport": "1",
          "AverageRating": "0",
          "TotalUser": "0"
        }
      ],
      "pagination": 6,
      "Sold": 50,
      "UnSold": 50
    }
  ]
};